name: Простой CI

on:
  push:
    branches:
      -'*'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello"
      - name: System info
        run: echo "System - Ubuntu 20.04"
